import { useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Layout.module.css'
import { useAuth } from './Authentication/AuthContext'
import Link from 'next/link'

export default function Layout(props) {

  const {currentUser, logout} = useAuth()

  useEffect(() => {
    console.log(currentUser)
  
    
  }, [currentUser])
  

  return (
    <>
      <Head>
        <title>The Next Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.title}>
          <Link href="/">
            <h2>My Next Blog</h2>
          </Link>
        </div>
        <div className={styles.navbar}>
          <div className={styles.user}>
            {
              currentUser ? <p>{currentUser.displayName}</p> : null
            }
          </div>
          <div className={styles.buttons}>
          { currentUser ? <Link href={{ pathname: '/dashboard', query: { userid: currentUser.email } }}>
            {currentUser.displayName === 'admin' ? 'Admin Dashboard' : 'My Blogs'}
            </Link> :null }
          { currentUser ? <button className={styles.logoutBtn} onClick={logout}>Log out</button> : <Link href="/signup">Login</Link> }
          </div>
        </div>  
        {props.children}  

      </main>
    </>
  )
}
